// 3474. Lexicographically Smallest Generated String

/**
Example 1:

Input: str1 = "TFTF", str2 = "ab"

Output: "ababa"

Explanation:

The table below represents the string "ababa"
Index	T/F	Substring of length m
0	'T'	"ab"
1	'F'	"ba"
2	'T'	"ab"
3	'F'	"ba"
The strings "ababa" and "ababb" can be generated by str1 and str2.

Return "ababa" since it is the lexicographically smaller string.

Example 2:

Input: str1 = "TFTF", str2 = "abc"

Output: ""

Explanation:

No string that satisfies the conditions can be generated.

Example 3:

Input: str1 = "F", str2 = "d"

Output: "a"

 
*/
const str1 = "F",
  str2 = "d";
function lexicographicallySmallest(str1: string, str2: string): string {
  const n = str1.length;
  const m = str2.length;
  const N = n + m - 1;
  let W = new Array(N).fill("?");

  // 1. Force rigidly defined assignments required by 'T' constraints
  for (let i = 0; i < n; i++) {
    if (str1[i] === "T") {
      for (let j = 0; j < m; j++) {
        let pos = i + j;
        if (W[pos] !== "?" && W[pos] !== str2[j]) {
          return "";
        }
        W[pos] = str2[j];
      }
    }
  }

  let F_indices: number[] = [];
  for (let i = 0; i < n; i++) {
    if (str1[i] === "F") {
      F_indices.push(i);
    }
  }

  // Status tracking structure for 'F' conditions
  let dead = new Uint8Array(n);
  let unassigned_cnt = new Int32Array(n);
  let unassigned_sum = new Int32Array(n);

  for (let i of F_indices) {
    let cnt = 0;
    let sum = 0;
    let is_dead = false;
    for (let j = 0; j < m; j++) {
      let pos = i + j;
      if (W[pos] === "?") {
        cnt++;
        sum += pos;
      } else {
        if (W[pos] !== str2[j]) {
          is_dead = true;
          break;
        }
      }
    }
    if (is_dead) {
      dead[i] = 1;
    } else {
      if (cnt === 0) return "";
      unassigned_cnt[i] = cnt;
      unassigned_sum[i] = sum;
    }
  }

  let F_containing: number[][] = Array.from({ length: N }, () => []);
  for (let i of F_indices) {
    for (let j = 0; j < m; j++) {
      F_containing[i + j].push(i);
    }
  }

  let forbidden_count = Array.from({ length: N }, () => new Int32Array(26));
  let num_forbidden = new Int32Array(N);

  for (let i of F_indices) {
    if (dead[i] === 0 && unassigned_cnt[i] === 1) {
      let rem_v = unassigned_sum[i];
      let f_idx = str2.charCodeAt(rem_v - i) - 97;
      forbidden_count[rem_v][f_idx]++;
      if (forbidden_count[rem_v][f_idx] === 1) {
        num_forbidden[rem_v]++;
      }
      if (num_forbidden[rem_v] === 26) {
        return "";
      }
    }
  }

  let vars_to_assign: number[] = [];
  for (let i = 0; i < N; i++) {
    if (W[i] === "?") {
      vars_to_assign.push(i);
    }
  }

  let var_idx = 0;
  let c_code_state = new Int32Array(vars_to_assign.length);
  let changes_stack: number[][][] = Array.from(
    { length: vars_to_assign.length },
    () => [],
  );

  // Iterative Backtracking avoiding deep-chain Call Stack limit bounds limit
  while (var_idx >= 0 && var_idx < vars_to_assign.length) {
    let v = vars_to_assign[var_idx];
    let advanced = false;

    while (c_code_state[var_idx] < 26) {
      let c_code = c_code_state[var_idx];
      c_code_state[var_idx]++;

      if (forbidden_count[v][c_code] > 0) continue;

      let c = String.fromCharCode(97 + c_code);
      let changes: number[][] = [];
      let possible = true;

      let f_list = F_containing[v];
      for (let i = 0; i < f_list.length; i++) {
        let f_idx_window = f_list[i];
        if (dead[f_idx_window] === 1) continue;

        if (c === str2[v - f_idx_window]) {
          if (unassigned_cnt[f_idx_window] === 1) {
            possible = false;
            break;
          }

          unassigned_cnt[f_idx_window] -= 1;
          unassigned_sum[f_idx_window] -= v;
          changes.push([0, f_idx_window, v]); // 0 equates to operation `dec`

          if (unassigned_cnt[f_idx_window] === 1) {
            let rem_v = unassigned_sum[f_idx_window];
            let f_c_idx = str2.charCodeAt(rem_v - f_idx_window) - 97;

            forbidden_count[rem_v][f_c_idx]++;
            if (forbidden_count[rem_v][f_c_idx] === 1) {
              num_forbidden[rem_v]++;
            }
            changes.push([1, rem_v, f_c_idx]); // 1 equates to operation `forbid`

            if (num_forbidden[rem_v] === 26) {
              possible = false;
              break;
            }
          }
        } else {
          dead[f_idx_window] = 1;
          changes.push([2, f_idx_window, 0]); // 2 equates to operation `dead`

          if (unassigned_cnt[f_idx_window] === 1) {
            let rem_v = unassigned_sum[f_idx_window];
            let f_c_idx = str2.charCodeAt(rem_v - f_idx_window) - 97;

            forbidden_count[rem_v][f_c_idx]--;
            if (forbidden_count[rem_v][f_c_idx] === 0) {
              num_forbidden[rem_v]--;
            }
            changes.push([3, rem_v, f_c_idx]); // 3 equates to operation `unforbid`
          }
        }
      }

      if (possible) {
        W[v] = c;
        changes_stack[var_idx] = changes;
        var_idx++;
        advanced = true;
        break;
      } else {
        for (let k = changes.length - 1; k >= 0; k--) {
          let change = changes[k];
          let typ = change[0];
          if (typ === 0) {
            unassigned_cnt[change[1]]++;
            unassigned_sum[change[1]] += change[2];
          } else if (typ === 1) {
            let rem_v = change[1],
              f_c_idx = change[2];
            forbidden_count[rem_v][f_c_idx]--;
            if (forbidden_count[rem_v][f_c_idx] === 0) num_forbidden[rem_v]--;
          } else if (typ === 2) {
            dead[change[1]] = 0;
          } else if (typ === 3) {
            let rem_v = change[1],
              f_c_idx = change[2];
            forbidden_count[rem_v][f_c_idx]++;
            if (forbidden_count[rem_v][f_c_idx] === 1) num_forbidden[rem_v]++;
          }
        }
      }
    }

    if (!advanced) {
      // Retreating mechanism
      c_code_state[var_idx] = 0;
      var_idx--;
      if (var_idx >= 0) {
        let changes = changes_stack[var_idx];
        for (let k = changes.length - 1; k >= 0; k--) {
          let change = changes[k];
          let typ = change[0];
          if (typ === 0) {
            unassigned_cnt[change[1]]++;
            unassigned_sum[change[1]] += change[2];
          } else if (typ === 1) {
            let rem_v = change[1],
              f_c_idx = change[2];
            forbidden_count[rem_v][f_c_idx]--;
            if (forbidden_count[rem_v][f_c_idx] === 0) num_forbidden[rem_v]--;
          } else if (typ === 2) {
            dead[change[1]] = 0;
          } else if (typ === 3) {
            let rem_v = change[1],
              f_c_idx = change[2];
            forbidden_count[rem_v][f_c_idx]++;
            if (forbidden_count[rem_v][f_c_idx] === 1) num_forbidden[rem_v]++;
          }
        }
      }
    }
  }

  return var_idx === vars_to_assign.length ? W.join("") : "";
}

console.log(lexicographicallySmallest(str1, str2));
